apiVersion: v1
kind: Service
metadata:
  name: taskflow-back
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: 'false'
spec:
  selector:
    app: taskflow-back
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-back
  labels:
    app: taskflow-back
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: taskflow-back
  template:
    metadata:
      labels:
        app: taskflow-back
    spec:
      containers:
        - name: taskflow
          image: clap.kr-central-2.kcr.dev/taskflow/taskflow-server:${IMAGE_TAG}
          imagePullPolicy: Always
          command: [ "java", "-jar", "app.jar" ]
          args: [ "--spring.profiles.active=prod" ]
          env:
            - name: TZ
              value: "Asia/Seoul"
          envFrom:
            - secretRef:
                name: taskflow-back
          ports:
            - containerPort: 9090
      restartPolicy: Always
      nodeSelector:
        label: "back"
      imagePullSecrets:
        - name: kc-cr-secret