spring:
  config:
    import:
      - mysql.yml
      - swagger.yml
      - redis.yml
      - optional:classpath:env.properties
    name: taskflow
web.resources.add-mappings: false

server:
  port: ${APPLICATION_PORT:8080}
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: dev



---
spring.config.activate.on-profile: prod
