spring.profiles.active: local

spring:
  jpa:
    hibernate:
      ddl-auto: none
  config:
    import:
      - mysql.yml
      - swagger.yml
      - redis.yml
      - optional:classpath:env.properties
  application:
    name: taskflow2

web.resources.add-mappings: false

server:
  port: ${APPLICATION_PORT:8080}
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
    taskflow.clap.server: DEBUG

---
spring.config.activate.on-profile: local
logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: dev
logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: prod
logging:
  level:
    root: INFO
---
