spring.profiles.active: local

spring:
  config:
    import:
      - mysql.yml
      - swagger.yml
      - redis.yml
      - auth.yml
      - elasticsearch.yml
      - s3.yml
      - notifications.yml
  application:
    name: taskflow
  web.resources.add-mappings: false


server:
  port: ${APPLICATION_PORT:8080}
  tomcat:
    max-connections: 10000
    threads:
      max: 600
      min-spare: 100
  domain:
    local: ${TASKFLOW_LOCAL_SERVER:127.0.0.1:8080}
    service: ${TASKFLOW_SERVICE_SERVER:127.0.0.1:8080}

web:
  domain:
    local: ${TASKFLOW_LOCAL_WEB:127.0.0.1:5173}
    service: ${TASKFLOW_SERVICE_WEB:127.0.0.1:5173}

local: ${TASKFLOW_LOCAL_WEB:127.0.0.1:5173}
service: ${TASKFLOW_SERVICE_WEB:127.0.0.1:5173}

#logging:
#  level:
#    root: INFO
#    taskflow.clap.server: ERROR
#    org:
#      springframework: DEBUG

---
spring.config.activate.on-profile: local
logging:
  level:
    root: INFO
    taskflow.clap.server: ERROR
#    org:
#      springframework: DEBUG

---
spring.config.activate.on-profile: dev
logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: prod
logging:
  level:
    root: INFO

cloud:
  kakao:
    project-id: 34481374c1ee4bbb8745df43e4c13fff
    region: kr-central-2
    object-storage:
      endpoint: https://objectstorage.kr-central-2.kakaocloud.com
      access-key: 253474a41cb447f4ad3c38e0ed9963c4
      secret-key: 74861656e46845488ec4357f155fa3ed
      bucket-name: taskflow

webhook:
  kakaowork:
    url: https://api.kakaowork.com/v1/messages.send_by_email
    auth: Bearer 1b01becc.a7f10da76d2e4038948771107cfe5c1d
  agit:
    url: https://agit.io/webhook/a342181d-fb18-4eb0-a99a-30f4fb5b14b1
