spring.profiles.active: local

spring:
  config:
    import:
      - mysql.yml
      - swagger.yml
      - redis.yml
      - auth.yml
      - elasticsearch.yml
      - s3.yml
      - notifications.yml
  application:
    name: taskflow
  web.resources.add-mappings: false


server:
  port: ${APPLICATION_PORT:8080}
  tomcat:
    max-connections: 10000
    threads:
      max: 600
      min-spare: 100
  domain:
    local: ${TASKFLOW_LOCAL_SERVER:127.0.0.1:8080}
    service: ${TASKFLOW_SERVICE_SERVER:127.0.0.1:8080}

web:
  domain:
    local: ${TASKFLOW_LOCAL_WEB:127.0.0.1:5173}
    service: ${TASKFLOW_SERVICE_WEB:127.0.0.1:5173}

local: ${TASKFLOW_LOCAL_WEB:127.0.0.1:5173}
service: ${TASKFLOW_SERVICE_WEB:127.0.0.1:5173}

#logging:
#  level:
#    root: INFO
#    taskflow.clap.server: ERROR
#    org:
#      springframework: DEBUG

---
spring.config.activate.on-profile: local
logging:
  level:
    root: INFO
    taskflow.clap.server: ERROR
#    org:
#      springframework: DEBUG

---
spring.config.activate.on-profile: dev
logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: prod
logging:
  level:
    root: INFO
