spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:taskflow}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

---
spring.config.activate.on-profile: local

spring:
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration/dev
  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

logging:
  level:
    ROOT: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.sql: debug
    org.hibernate.type: trace
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.orm: TRACE
    org.springframework.transaction: TRACE
    com.zaxxer.hikari: TRACE
    com.mysql.cj.jdbc: TRACE

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/dev

---
spring.config.activate.on-profile: prod

spring:
  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/prod