spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

webhook:
  kakaowork:
    url: ${KAKAOWORK_WEBHOOK_URL}
    auth: ${KAKAOWORK_WEBHOOK_AUTH}
  agit:
    url: ${AGIT_WEBHOOK_URL}