ALTER TABLE api_log
    MODIFY COLUMN log_status ENUM('LOGIN', 'LOGOUT', 'REQUEST_CREATED', 'REQUEST_UPDATED', 'REQUEST_CANCELLED',
    'REQUEST_APPROVED', 'ASSIGNER_CHANGED', 'COMMENT_ADDED',
    'COMMENT_UPDATED', 'STATUS_CHANGED', 'TASK_VIEWED') NOT NULL;